define([], function () {
  return {
    PropertyPaneDescription: "توضیحات",
    BasicGroupName: "نام گروه",
    DescriptionFieldLabel: "فیلد توضیحات",
    InventoryItemsListNameLabel: "نام لیست کالاهای موجود",
    InventoryTransactionListNameLabel: "نام لیست ورود و خروج موجودی",
    InventoryManagement: "مدیریت موجودی",
    CreateForm: "ایجاد فرم",
    Date: "تاریخ",
    FormNumber: "شماره فرم",
    TransactionType: "نوع اقدام",
    In: "ورودی",
    Out: "خروجی",
    Item: "مورد",
    Quantity: "مقدار",
    Notes: "یادداشت‌",
    Actions: "اقدامات",
    AddRow: "افزودن ردیف",
    Submit: "ثبت",
    Cancel: "لغو",
    Required: "ضروری",
    Remove: "حذف",
  };
});
